### ISSUE TITLE
Suggestion: Do not center justify in child creator

### ISSUE THREAD

**Issue by blak3r** [paulsheldon/SmartThings-PS#12]
As a user, the center justification led me to initially think that certain things were nested under others. 

![image](https://user-images.githubusercontent.com/1581785/73470137-6c829600-4355-11ea-9d2f-f879f3bc146b.png)

For example, I thought Run Routine was like nested under Fans at first glance.

**Comment by paulsheldon** [comment]
Mm it wasn’t like that before, let me check on my device    

 

I cant see anything in the code that has changed since Nov that would produce that, was it like it on the previous version?

**Comment by paulsheldon** [comment]
Can you try again go into smart apps, there should be a magnifying glass by child creator, click and it should allow you to save master version over local. 

 

See if that fixes it

**Comment by blak3r** [comment]
It's always been that way.  The screenshot i provided was on an iphone 11 pro, with smarthings classic app.  I just looked at it in the new smarthings app and it does look a lot prettier.

FYI: I deployed master to my phone this morning and can confirm I got the icons.


Newer smarthings app:
![image](https://user-images.githubusercontent.com/1581785/73484365-29cdb780-436f-11ea-8a2f-d24e7b6569ac.png)

**Comment by paulsheldon** [comment]
There is currently no way to justify this menu better
