### ISSUE TITLE
Adding support for WD200+

### ISSUE THREAD

**Issue by myclue** [paulsheldon/SmartThings-PS#13]
I've added this locally in my child code to support the HomeSeer WD200+ Dimmer based on the WD100+ Dimmer code and https://helpdesk.homeseer.com/article/177-smartthings-handler-wd200

Can this be merged into the trunk in the future?
Thanks!

    if (state.buttonType.contains("WD200+ Dimmer")) {
        switch (state.currentButton) {
            case 1: return "Double-Tap Upper Paddle"; break
            case 2: return "Double-Tap Lower Paddle"; break
            case 3: return "Triple-Tap Upper Paddle"; break
            case 4: return "Triple-Tap Lower Paddle"; break
            case 5: return "Press & Hold Upper Paddle\n(See user guide for quirks)"; break
            case 6: return "Press & Hold Lower Paddle\n(See user guide for quirks)"; break
            case 7: return "Single Tap Upper Paddle\n(See user guide for quirks)"; break
            case 8: return "Single Tap Lower Paddle\n(See user guide for quirks)"; break
            case 9: return "4X-Tap Upper Paddle"; break
            case 10: return "4X-Tap Lower Paddle"; break
            case 11: return "5X-Tap Upper Paddle"; break
            case 12: return "5X-Tap Lower Paddle"; break
        }
    }

**Comment by paulsheldon** [comment]
Thanks & yes I will make a pull request to get his added to the code. I’ve just released an update today which was due out on 1st Feb so I may see if I can squeeze this in before then

 

Can you confirm the following mapping are correct as these will be used within the code. 

 

It looks like this can be used for both the WS200+ & the WD200+ so I shall add the code for both devices

 

 

Many thanks 

 

Paul Sheldon

**Comment by myclue** [comment]
Yes, I just verified that these mappings work for both WD200+ and WS200+
I only own the WD200+, but I found the WS200+ mappings here:
https://helpdesk.homeseer.com/article/178-smartthings-handler-ws200

**Comment by paulsheldon** [comment]
Great all I need to do then is get the names for the images files

 

If your not using the latest version could you add the following line of code (log.debug picNameNoSpace) in the getButtonSections and let me know what is seen in the relevant button mapping log file. It should dsay ??????.png not found

 

Once I have this I can upload the code in time for 1st Feb

 

def getButtonSections(buttonNumber) {
    return {
        def picNameNoSpace = "${state.buttonType}${state.currentButton}.png" - " " - " " - " " - "/" - "-"
        log.debug picNameNoSpace

**Comment by myclue** [comment]
Log shows files like
WD200+Dimmer1.png
WD200+Dimmer2.png
...
WD200+Dimmer12.png

I don't have a WS200+ switch but I'm guessing the image files will start with WS instead of WD.

**Comment by paulsheldon** [comment]
This has now been completed and is in the version released today
