### ISSUE TITLE
I get an error when I want to add it to SmartApps

### ISSUE THREAD

**Issue by orenatan** [paulsheldon/SmartThings-PS#17]
No signature of method: script_app_metadata_8693cc69_8b86_44c5_b252_656c4081e57e.metadata() is applicable for argument types: (script_app_metadata_8693cc69_8b86_44c5_b252_656c4081e57e$_run_closure1) values: [script_app_metadata_8693cc69_8b86_44c5_b252_656c4081e57e$_run_closure1@4cb6fa4c] Possible solutions: getMetadata(), getState(), setState(java.lang.Object), metaClass(groovy.lang.Closure)

**Comment by saiajin** [comment]
I get this as well

**Comment by uSlackr** [comment]
Worked fine for me.  I did this
Create new SMart app
On From Form page add name, namespace, author and desc.
On From code tab, insert code from abd-manager.src
Create App, Publish For ME

Create new Smart App
On From Form, add similar details
On code tab insert code from abc-child-creatpr.src
Create App
DO NOT PUBLISH
Add app in Smartapp on phone

**Comment by paulsheldon** [comment]
I hope this is now fixed, if not please try the new version o the develop branch which has been updated today. This should fix any installation problems
