### ISSUE TITLE
Hue Dimmer

### ISSUE THREAD

**Issue by rwilson-r7** [paulsheldon/SmartThings-PS#8]
Anyone notice any issues with the hue dimmer, events are captured just no actions are taken I have all mappings in manager configured etc no errors in logs..

**Comment by paulsheldon** [comment]
Hi, A few things to check

Has it just stopped working or is a new device? 
Are you using my device driver for the Hue dimmer?
Have you set the option to use Button Number in the Hue Dimmer Options?

**Comment by rwilson-r7** [comment]
Yea its a new device, I am using the device driver I am not totally sure about the button number thing.. The device is showing up and when pressed I can see the press in logs just nothing happens after the press if that makes sense.. I might remove every thing and start from scratch and see if that helps maybe, thanks!

**Comment by paulsheldon** [comment]
HI did you resolve this problem? If its still an issue could you login to the SmartThings IDE and send me any message from the Live Logging screen when you push a button. Thanks

**Comment by rwilson-r7** [comment]
I gave up tbh and am using a different switch I would say if no one else has seen it then it was something I done on my end thanks for chasing it back up though!
